"""Add users table and owner_id to habits

Revision ID: d0e14185a351
Revises: 
Create Date: 2025-11-02 22:02:59.136519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e14185a351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'habits', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'owner_id')
    # ### end Alembic commands ###
